Feat/database routes
caiotcunha/foodFit pull request #4
Opened 2023-04-21 18:55 UTC by HenriqueRotsen

Fazendo as rotas de dietas

2023-04-21 21:32 UTC, IvanAssis07 requested changes
Dá uma olhada nos comentários que eu deixei ali como vc deve fazer pro get funcionar e também comentário para apagar. Vou deixar para vc fazer essas mudanças e depois eu aprovo.

2023-04-21 21:32 UTC, IvanAssis07 commented on api/src/domains/diets/controllers/index.js
> +router.get('/:UserId', async (req, res, next) => {
Como falei no aúdio é só você nomear as rotas diferentes para os xpress pegar elas certo: 
Aí troca o nome dessa primeira porque é um getAll específico. Coloca assim: router.get('/userDiets/:UserId' ....

2023-04-21 21:32 UTC, IvanAssis07 commented on api/src/domains/diets/controllers/index.js
> +router.get('/:UserId/:id', async (req, res, next) => {
Depois de mudar o get ali em cima, nesse daqui se você deixar:
router.get(':dietId' ....

Nesse caso faz dietId ao invés de só id para ficar mais claro.

2023-04-21 21:32 UTC, IvanAssis07 commented on api/src/domains/diets/controllers/index.js
>  // Get All Diets (do user)
Apagar comentário

2023-04-21 21:32 UTC, IvanAssis07 commented on api/src/domains/diets/controllers/index.js
>  // Get by ID
Apagar comentário

2023-04-21 21:32 UTC, IvanAssis07 commented on api/src/domains/diets/controllers/index.js
>  // Create
Apagar comentário

2023-04-22 15:03 UTC, HenriqueRotsen commented
Fiz as alterações, porém continua um bug no get by id das dietas

2023-04-22 15:07 UTC, HenriqueRotsen commented
Fiz as alterações, porém continua um bug no get by id das dietas

2023-04-22 18:52 UTC, IvanAssis07 approved these changes

2023-04-22 18:53 UTC, merged